ADMIN_TOKEN: ENC[AES256_GCM,data:FS+EFbjbnYX22gMc/4mMy1qVKFsMtDUiex4RUbzYsJR2wRAjFpA/4oP8BeAKZVEs+krHo+LXXzg9QlTEu1JjSLNq4ug59vu1HR/Zux+4nF/DHb641LXDEwu4FpV6YqiJ/dGjbAJnUqbkUbHsDZzh2mKsorMQRQ==,iv:MaY5kBeMVBtwdFhULHUR1mpJ/zueDT/T1MwyOL2iTgs=,tag:v6T9vLXc+WYryGdOi1exjQ==,type:str]
sops:
    age:
        - recipient: age1595c6n7r3zu0aql8qeehlulds6g4cvavmphsyauk9uddks5hpuzqcg7c4u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISGh2ck1KejhsQjFqRk0w
            R1VGZStHcW1jVnNlVEdrWHYwanhhU0Q1d21VCkN6aXJ0SWo1WXdpNStRRzE2SXV2
            OXhZS2NjUHNGZi9VcndZdE0vdlNlTHMKLS0tIEVrVTR4dmUyVjU0eU10VURKTTlP
            d0xpeDdzV2xtMHVaSGxEaUU1YzkwaFkKgRC8gTCEv+M+UFOII8gOsAkoqyETUT2a
            YVXbqEUXKpT7G2Vw4H9mRklax8PDoOo/D13uVTNjZupdtzSUQV418g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T06:44:11Z"
    mac: ENC[AES256_GCM,data:KvXf/j3f1Wu0RiSWjvLls0DZRmaXsNnJN5UmT/61yeZns10eZTCltovpBa+CnoXL25uE08uF0fA1KgF4MLdTpTSSHlPBmb3VEe2876SLKR0VwdSKziIEdf+26SqzZvGn6Hcj6zBZTOe9F8dVOkk6oW0wX/0cLbsS/CIWbDTVpAY=,iv:PSYwd3cPmV1ntQyhNCqkL6T7wikvxG1R+UXyQHtYIBo=,tag:mIkpZCJm9Qvpk6BogVWGpg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
