#!/usr/bin/env bash

#MISE desccription "Setup Docker Compose Service for Authentik"
#MISE raw=true

echo "PG_PASS=$(openssl rand -base64 36 | tr -d '\n')" >> .env
echo "AUTHENTIK_SECRET_KEY=$(openssl rand -base64 60 | tr -d '\n')" >> .env
