PG_PASS: ENC[AES256_GCM,data:rFl/M/JESWcKoMdwqa8+nLpKjOSH4X9U6zbAZLEZ9TUFiAPkIh+kRe0SUgwWkTwC,iv:te8LvxdZ7SNx/kTQvKL6X68SUFaNhu0wUFdNi+4r8DM=,tag:mMloAbNgmJkHR05oKy3+7Q==,type:str]
AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:yrzavmHorfeGMVvagnntJFxZVN6AqvriX/DeMZbFnCmSQP0Z6LZ0vuHLrIPM/RBfu3PushztaLVDf6e6rAAyPYidvJvpRSZtMVxYujfzY5s=,iv:CaXKITKfnPINl9y7TjnlyCGIFnXvF6PvtuCc+tFam9c=,tag:CQd4eFpJMCjQmGVQrne+qA==,type:str]
sops:
    age:
        - recipient: age1595c6n7r3zu0aql8qeehlulds6g4cvavmphsyauk9uddks5hpuzqcg7c4u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVDFESmlCQ0Rtb1haUHE2
            SE05ZFQrVWJ4SXk2VlVkN0lOKzV5YzR4Z0VVCmpqNGVrZG42UnFiNFRNb3NMYmhi
            cTQ5YWt4S09HTlhwbVVNUlh6b0VialUKLS0tIFhCbmwrSTBpcGFUdy90aUJmVEVQ
            N2ZxNVZKa0w5Q3lVL2RydktOOVpXWWcKQ3L5S/8Mrec3IPoK7cdRlkDiWXLbhzoW
            lL+XigO7RWHQvzbP3ciB28IUkD1KRqowkUtApttxukmJ5Hljx1Xorg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T16:37:20Z"
    mac: ENC[AES256_GCM,data:8hT8S0lP1rwSqTxVuKXcAZ4L4td+Oy6BQuRvdpbU9TqMfymgz1M4egPQzphxTgSFnn7xD8dhmqhlCHOdv4khx2XS92TylakcexEJqZ30XL3Vh28FKi6+M2e0zu+GRDGlzWiFQ0gOxHyJd4cPYtX+wLCzL76I1FK1wOzHi4+IMHU=,iv:rt/dBZwhNl832Hl9cZOw8l5LLigOk6HZa5I6+7kIwf4=,tag:Iu2QC8qDPgP7h8Dkzl8sfw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
